name: Build Desktop App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Libraries
      run: |
        pip install flask pyinstaller

    # Yahan humne --icon="icon.ico" ka izafa kiya hai
    - name: Convert to EXE
      run: |
        pyinstaller --onefile --windowed --icon="icon.ico" --add-data ".;." app.py

    - name: Upload Final EXE
      uses: actions/upload-artifact@v4
      with:
        name: Avelia-Game-App
        path: dist/*.exe
